# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[(1, 'India'), (0, 'Other')], default='India', max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('yearOfStudy', models.IntegerField()),
                ('accommodation', models.BooleanField()),
                ('auth_token', models.CharField(max_length=500)),
                ('tokenCreatedAt', models.TimeField()),
                ('createdAt', models.TimeField()),
                ('updatedAt', models.TimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
