# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='uname',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(default='111111', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='auth_token',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2017, 12, 29, 15, 23, 47, 173289)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='updatedAt',
            field=models.TimeField(default=datetime.datetime(2017, 12, 29, 15, 23, 47, 173314)),
        ),
    ]
