# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20171229_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='createdAt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='updatedAt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
