# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20171229_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
