# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20171229_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='tokenCreatedAt',
            field=models.DateTimeField(),
        ),
    ]
