# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20171229_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(choices=[(1, 'india'), (0, 'other')], default='India', max_length=100),
        ),
    ]
