# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20171231_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='yearOfStudy',
            new_name='YoS',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='passwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(choices=[('india', 'India'), ('other', 'Other')], default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
