# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20180101_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='unique',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='YoS',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='tokenCreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
