# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_eventregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='type',
            field=models.CharField(choices=[('event', 'event'), ('workshop', 'workshop')], default='event', max_length=20),
        ),
    ]
