# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20180110_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='unique',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
