# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_eventdetails_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='caption',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
