# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20180113_1720'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventregister',
            table='registration',
        ),
    ]
