# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20180119_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='require_payment',
            field=models.BooleanField(default=False),
        ),
    ]
