# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_userdetails_events_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=200)),
                ('days', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('check_in', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.UserDetails')),
            ],
            options={
                'db_table': 'hospi',
            },
        ),
    ]
