# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_userdetails_alt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='alt_phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
