# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20180216_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='ticket',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
