# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_userdetails_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospi',
            name='check_out',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
