# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_hospi_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospi',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
