# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_auto_20180217_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='paid_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='amount_online',
            field=models.IntegerField(default=0),
        ),
    ]
