version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - .:/pma
    ports:
      - "8080:80"