version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  nginx:
    image: nginx:latest
    container_name: synergy_nginx
    volumes:
      - .:/code
      - ./configs/nginx:/etc/nginx/conf.d
      - ./prod/static:/static
    ports:
      - "80:8000"
    depends_on:
      - web
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - .:/pma
    ports:
      - "8080:80"
